info:
  contact: {}
  description: API for culinary recipes (BMSTU Team development project)
  title: TeamDev API
  version: "0.1"
paths:
  /categories:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves all categories
      tags:
      - Categories
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
