info:
  contact: {}
  description: API for culinary recipes (BMSTU Web development cource project)
  title: Recipes API
  version: "0.1"
paths:
  /categories:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves all categories
      tags:
      - Categories
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
