name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Build 
      run: |
        cd backend
        go build -v ./...
    - name: UnitTest
      run: |
        cd backend
        go test -v -coverpkg ./models/ ./models/tests/unit/
